// "watch:tailwind": "postcss public/tailwind.css -o public/index.css -w",
// "build:tailwind": "NODE_ENV=production postcss public/tailwind.css -o public/index.css",
// "dev": "run-p start:dev autobuild watch:tailwind",
// "build": "npm run build:tailwind && rollup -c",
// "start": "sirv public --single",
// "start:dev": "sirv public --single --dev",
// "autobuild": "rollup -c -w",